# Generated by Django 5.2.6 on 2025-11-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('storage', 'Storage Devices'), ('cables', 'Cables'), ('motherboard', 'Motherboards'), ('processor', 'Processors'), ('ram', 'RAM'), ('gpu', 'Graphics Cards'), ('peripheral', 'Peripherals'), ('others', 'Others')], max_length=50)),
                ('productName', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('storage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('cable_type', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('cores', models.CharField(blank=True, max_length=50, null=True)),
                ('clock_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_size', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('vram', models.CharField(blank=True, max_length=50, null=True)),
                ('chipset', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.IntegerField()),
                ('Address', models.CharField(blank=True, max_length=25)),
                ('Place', models.CharField(blank=True, max_length=15)),
                ('District', models.CharField(blank=True, max_length=15)),
                ('State', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
