# Generated by Django 5.2.6 on 2025-11-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shop', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
